apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: aqvylwt0r-nodejs 
  janus-idp.io/tekton: aqvylwt0r-nodejs
  backstage.io/kubernetes-id: aqvylwt0r-nodejs
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: aqvylwt0r-nodejs
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml