apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: aqvylwt0r-nodejs
  janus-idp.io/tekton: aqvylwt0r-nodejs
  backstage.io/kubernetes-id: aqvylwt0r-nodejs
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: aqvylwt0r-nodejs
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
